### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by LambdAurora — CHANGES_REQUESTED** [review]
I prefer to merge complete translations than incomplete ones.
I judge subtitles very important too.

**Comment by LambdAurora** [comment]
Closed by #2.

**Comment by ghost** [comment]
I see. I'll pay more attention next time

**Comment by aokeluolai** [comment]
> I prefer to merge complete translations than incomplete ones.
> I judge subtitles very important too.
I see. I'll pay more attention next time

**Pull request closed without merging**
